### ISSUE TITLE
이슈 남기는 방법 문의합니다!

### ISSUE THREAD

**Issue by HeesungB** [sunghyunzz/android-clean-architecture-example#2]
두가지 이슈(Todo 컨텐츠 추가, Todo Done처리) 추가하려고 하는데 혹시 이슈 추가하는 템플릿이나 방식이 있을까요?

**Comment by HeesungB** [comment]
추가적으로 영어로 해야하는지 한국어로 해도 괜찮은지 궁금합니다!

**Comment by 0xd669** [comment]
확인이 늦어 죄송합니다.

1. 따로 템플릿은 없습니다. 자유롭게 작성해주시면 됩니다 :)
1. 저는 영어와 한국어 둘 다 상관없을 것 같습니다.

**Comment by HeesungB** [comment]
넵 감사합니다 천천히라도 진행 해볼께요
